### ISSUE TITLE
Blocking DMX addresses does not work

### ISSUE THREAD

**Issue by janherbst** [ISD-Sound-and-Lights/eyepatch#9]
Added 5 fixtures, blocked addresses 1-100; generated CSV put addresses within 1-100

**Comment by il8677** [comment]
Fixed, problem was caused by for loop that tried to find if DMX allocation space was big enough. It searched up to the size of the required space. So if a fixture set needed 47 addresses, it would only search up to DMX 47 regardless of the current starting address it was looking at. So if it was looking at starting the patch at DMX patch 5, it should be looking up to patch 52, since thats the required space, but instead, it would only look up to 47. Fix was changing for-loop to end at required space + starting patch.
